dashboard/urls.py
from django.urls import path
from dashboard import views as dashboard_views

urlpatterns = [
    path('dashboard/', dashboard_views.DashboardView.as_view(), name='dashboard'),
    path('dashboard/get_account_chart/', dashboard_views.get_account_chart, name='get_account_chart'),
    path('dashboard/get_job_chart/', dashboard_views.get_job_chart, name='get_job_chart'),

]

job/urls.py
from django.urls import path
from job import views as job_views
from job import api_views as job_api_views

urlpatterns = [
    path('jobs/job_list/', job_views.JobListView.as_view(), name='job_list'),
    path('jobs/submit_job/', job_views.SubmitJobView.as_view(), name='submit_job'),
    path('jobs/job_output_url/', job_views.job_output_url, name='job_output_url'),
    path('jobs/submit_file_select/get_file_select/', job_views.get_file_select, name='get_file_select'),
    path('jobs/submit_file_select/', job_views.SubmitFileSelectView.as_view(), name='submit_file_select'),
    path('jobs/advanced_keyshot_submitter/', job_views.AdvancedSubmitterView.as_view(), name='advanced_keyshot_submitter'),
    path('jobs/advanced_keyshot_submitter/<uuid:session_id>/', job_views.AdvancedSubmitterView.as_view(), name='advanced_keyshot_submitter'),
    path('jobs/advanced_keyshot_submitter/<str:file_name>/', job_views.AdvancedSubmitterView.as_view(), name='advanced_keyshot_submitter'),
]

# api routes
urlpatterns += [
    path('api-job/job/', job_api_views.JobAPI.as_view()),
    path('api-job/submit_session/', job_api_views.SubmitSessionAPI.as_view()),
]

payment/urls.py
from django.urls import path, re_path
from payment import views as payment_views

urlpatterns = [
    path('payment/', payment_views.PaymentView.as_view(), name='payment'),
    path('payment/cancelled/', payment_views.PaymentView.payment_cancelled, name='payment_cancelled'),
    path('payment/processed/', payment_views.PaymentView.payment_processed, name='payment_processed'),
    path('invoices/', payment_views.InvoiceView.as_view(), name='invoices'),
    path('invoices/generate_invoice/', payment_views.GeneratePDF.as_view(), name='generate_invoice'),
]

users/urls.py
from django.urls import path, re_path, include
from users import views as users_views


urlpatterns = [
    path('', users_views.Login.as_view(), name='user_login'),
    path('register/', users_views.Register.as_view(), name='register'),
    path('profile/', users_views.Profile.as_view(), name='profile'),
    path('password_reset/', users_views.UserPasswordResetView.as_view(), name='user_password_reset'),
    path('password_change/', users_views.UserPasswordChangeView.as_view(), name='user_password_change'),
    path('reset/<uidb64>/<token>/', users_views.UserPasswordResetConfirmView.as_view(),
         name='user_password_reset_confirm'),
    path('activate/', users_views.activate, name='activate'),
    path('activate/<slug:username>/', users_views.activate, name='activate'),
    path('activate/<slug:username>/<slug:token>/', users_views.activate, name='activate'),
]

# user rest framework api urls
urlpatterns += [
    path('api-user/user/', users_views.UserAPI.as_view()),
]

dashboard/models.py
from django.db import models

# Create your models here.

job/models.py
import os
import json
import uuid

from django.urls import reverse
from django.template.loader import render_to_string
from django.forms.models import model_to_dict
from django.db import models
from django.db.models.signals import post_save, pre_delete, pre_save
from django.contrib.auth.models import User
from django.contrib.postgres.fields import ArrayField
from django.utils.translation import gettext_lazy as _

from channels.layers import get_channel_layer
from asgiref.sync import async_to_sync

from job import utils as job_utils
from payment.models import *
from system.models import SocketConnection
from rendershot_django.utils import post_message_to_slack


channel_layer = get_channel_layer()


class SoftwareVersionStatus(models.TextChoices):
    API = 'API', _('API')
    WEBANDAPI = 'web_and_api', _('Web and API')


class JobStatus(models.Model):

    name = models.CharField(max_length=50, null=True, blank=True)
    display_name = models.CharField(max_length=50, null=True, blank=True)
    admin_only = models.BooleanField(default=False, null=True)
    description = models.CharField(max_length=500, null=True, blank=True)
    is_suspendable = models.BooleanField(default=False, null=True)
    is_deletable = models.BooleanField(default=False, null=True)
    is_upgradable = models.BooleanField(default=False, null=True)

    @classmethod
    def post_create(cls, sender, instance, created, *args, **kwargs):
        pass

    def __str__(self):
        return self.display_name


class OutputFormat(models.Model):

    extension = models.CharField(max_length=10, null=True, blank=True)

    @classmethod
    def post_create(cls, sender, instance, created, *args, **kwargs):
        pass

    def __str__(self):
        return self.extension


class FileFormat(models.Model):

    extension = models.CharField(max_length=10, null=True, blank=True)

    @classmethod
    def post_create(cls, sender, instance, created, *args, **kwargs):
        pass

    def __str__(self):
        return self.extension


class RenderPlan(models.Model):

    name = models.CharField(max_length=50, null=True, blank=True)
    display_name = models.CharField(max_length=200, null=True, blank=True)
    rate_per_min = models.FloatField(default=0.0, null=True, blank=True)
    deadline_machine_limit = models.IntegerField(default=0, null=True)
    deadline_priority = models.IntegerField(default=1, null=True)
    admin_only = models.BooleanField(default=False, null=True)

    @classmethod
    def post_create(cls, sender, instance, created, *args, **kwargs):
        pass

    def __str__(self):
        return self.display_name


class FileStorage(models.Model):

    name = models.CharField(max_length=50, null=True, blank=True)
    setting = models.JSONField(max_length=5000, null=True, blank=True)

    @classmethod
    def post_create(cls, sender, instance, created, *args, **kwargs):
        pass

    def __str__(self):
        return self.name


class Software(models.Model):

    name = models.CharField(max_length=50, null=True, blank=True)

    @classmethod
    def post_create(cls, sender, instance, created, *args, **kwargs):
        pass

    def __str__(self):
        return self.name


class SoftwareVersion(models.Model):

    software = models.ForeignKey(Software, null=True, blank=True, on_delete=models.CASCADE)
    icon = models.FileField('Icon', upload_to='software/', blank=True,
                            null=True, default=f'/software/keyshot_logo.svg')
    version = models.CharField(max_length=50, null=True, blank=True)
    plugin_name = models.CharField(max_length=50, null=True, blank=True)
    file_format = models.ManyToManyField(FileFormat)
    output_format = models.ManyToManyField(OutputFormat)
    render_plan = models.ManyToManyField(RenderPlan)
    file_storage = models.ManyToManyField(FileStorage)
    access_type = models.CharField(max_length=100, null=True,
                                   choices=SoftwareVersionStatus.choices,
                                   default=SoftwareVersionStatus.WEBANDAPI)
    deadline_pool = models.CharField(max_length=50, null=True, blank=True)
    deadline_group = models.CharField(max_length=50, null=True, blank=True)

    @classmethod
    def post_create(cls, sender, instance, created, *args, **kwargs):
        pass

    def __str__(self):
        return self.version

    @property
    def output_formats(self):
        return self.output_format.all()

    @property
    def render_plans(self):
        return self.render_plan.exclude(admin_only=True).order_by('display_name')

    @property
    def file_formats(self):
        return self.file_format.all()

    @property
    def file_storages(self):
        return self.file_storage.all()


class JobError(models.Model):
    software = models.ForeignKey(Software, null=True, blank=True, on_delete=models.RESTRICT)
    error = models.CharField(max_length=500, null=True, blank=True)
    title = models.CharField(max_length=500, null=True, blank=True)
    description = models.TextField(max_length=2000, null=True, blank=True)
    solution = models.TextField(max_length=2000, null=True, blank=True)

    @classmethod
    def post_create(cls, sender, instance, created, *args, **kwargs):
        pass

    def __str__(self):
        return self.error


class Job(models.Model):
    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, null=True, blank=True)
    frame_list = ArrayField(models.CharField(max_length=50, blank=True, null=True))
    render_plan = models.ForeignKey(RenderPlan, null=True, blank=True, on_delete=models.RESTRICT)
    file_storage = models.ForeignKey(FileStorage, null=True, blank=True, on_delete=models.RESTRICT)
    output_format = models.ForeignKey(OutputFormat, null=True, blank=True, on_delete=models.RESTRICT)
    status = models.ForeignKey(JobStatus, null=True, blank=True, on_delete=models.RESTRICT)
    progress = models.FloatField(default=0.0, null=True, blank=True)
    software_version = models.ForeignKey(SoftwareVersion, null=True, blank=True, on_delete=models.RESTRICT)
    deadline_id = models.CharField(max_length=200, null=True, blank=True)
    data = models.JSONField(max_length=10000, null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    deadline_tasks_count = models.IntegerField(default=0, null=True)
    cost = models.FloatField(default=0.0, null=True, blank=True)
    error = models.ManyToManyField(JobError, blank=True)

    def __init__(self, *args, **kwargs):
        self.operator = 'web_admin'
        self.status_signals = {'on_suspended': self.on_suspended,
                               'on_suspending': self.on_suspending,
                               'on_completed': self.on_completed,
                               'on_failed': self.on_failed,
                               'on_deleted': self.on_deleted,
                               'on_submitted': self.on_submitted,
                               'on_rendering': self.on_rendering,
                               'on_resuming': self.on_resuming,
                               }

        self.plan_signals = {'on_plan_changed': self.on_plan_changed,
                             }

        super(Job, self).__init__(*args, **kwargs)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        pre_save_model = Job.objects.filter(pk=self.pk).first()

        if 'operator' in kwargs:
            self.operator = kwargs.pop('operator')

        super(Job, self).save(*args, **kwargs)

        call_status_signals = False
        call_plan_signals = False

        if not pre_save_model and self.status.name == 'submitted':
            call_status_signals = True
            self.user_socket_job_update('add_job')
        else:
            self.user_socket_job_update('update_job')

        if pre_save_model and pre_save_model.status.name != self.status.name:
            call_status_signals = True

        if call_status_signals:
            status_signal = self.status_signals.get(f'on_{self.status.name}', None)
            status_signal and status_signal()

        if pre_save_model and pre_save_model.render_plan.name != self.render_plan.name:
            call_plan_signals = True

        if call_plan_signals:
            plan_signal = self.plan_signals.get('on_plan_changed', None)
            plan_signal and plan_signal()

    @property
    def user_profile(self):
        return self.user.profile

    @classmethod
    def pre_save(cls, sender, instance, created=None, **kwargs):
        if created:
            return

        job_data = instance.data
        if job_data.get('session_id'):
            pass
        else:
            job_data['system_info']['plugin_name'] = instance.software_version.plugin_name
            job_data['system_info']['plugin_version'] = instance.software_version.version
            job_data['system_info']['render_plan'] = instance.render_plan.name
            job_data['system_info']['username'] = instance.user.username
            job_data['system_info']['output_format'] = instance.output_format.extension
            job_data['system_info']['storage_type'] = instance.file_storage.name
        instance.data = job_data

    @property
    def frames_count(self):
        tasks = self.jobtask_set.all()
        frames = 0
        for task in tasks:
            frames += len(eval(task.frame_list))

        return frames

    def count_by_status(self, status):
        return len(self.objects.filter(status=status))

    @property
    def count_rendering(self):
        return len(self.objects.filter(status=JobStatus.objects.filter(name='rendering').first()))

    @property
    def count_all(self):
        return len(self._meta.model.objects.all())

    @property
    def get_frame_list_display(self):
        if len(self.frame_list) > 1:
            return "Multiple Range"
        else:

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver
from django.utils.translation import gettext_lazy as _
import pytz
from rest_framework.authtoken.models import Token

from payment.models import PaymentStatus
from rendershot_django.utils import post_message_to_slack
from system.dbx_utils import DropboxHandler


class AccountTypes(models.TextChoices):
    PERSONAL = 'personal', _('Personal')
    COMPANY = 'company', _('Company')


class Profile(models.Model):

    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    account_type = models.CharField(max_length=100, null=True, choices=AccountTypes.choices, default=AccountTypes.PERSONAL)
    company_name = models.CharField(max_length=100, null=True)
    city = models.CharField(max_length=100, null=True)
    country = models.TextField(max_length=50, null=True, choices=pytz.country_names.items())
    address = models.CharField(max_length=1000, null=True)
    zip_code = models.CharField(max_length=100, null=True)
    phone = models.CharField(max_length=100, null=True)
    vat = models.CharField(max_length=100, null=True)
    payment_allowed = models.BooleanField(default=False, null=True)
    credit = models.FloatField(default=0.0, null=True)
    blocked = models.BooleanField(default=False, null=True)
    receive_job_email_notifs = models.BooleanField(default=True, null=True)
    ip_address = models.CharField(max_length=250, null=True)
    dropbox_outputs_share_link = models.CharField(max_length=250, null=True)
    rate_multiplier = models.FloatField(default=1.0, null=True)
    reset_password_required = models.BooleanField(default=False, null=True)
    chunk_size_override = models.IntegerField(default=1, null=True)

    def __str__(self):
        return self.user.username

    @property
    def total_payment(self):
        total = 0
        for payment in self.user.payment_set.all():
            if type(payment.amount) in [int, float] and payment.status == PaymentStatus.COMPLETED:
                total += payment.amount
        return total

    @property
    def payment_count(self):
        return len(self.user.payment_set.all())

    @property
    def ticket_count(self):
        return len(self.user.ticket_set.all())

    @property
    def job_count(self):
        return len(self.user.job_set.exclude(status__name='deleted').all())

    @property
    def balance(self):
        jobs = self.user.job_set.all()
        spent_amount = float()

        for job in jobs:
            spent_amount += job.cost

        balance = self.credit - (spent_amount * self.user.profile.rate_multiplier)
        return balance

    def is_network_rendering_allowed(self):
        return self.user.groups.filter(name='network_rendering').exists()


@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        Token.objects.create(user=instance)
        Profile.objects.create(user=instance)
        # TODO disable for ingestion
        post_message_to_slack("New Registration",
                              f"New User : {instance.username} Registered",
                              {'user': instance.username,
                               'email': instance.email})

    instance.profile.save()


@receiver(post_delete, sender=User)
def update_user_dropbox(sender, instance, **kwargs):

    # TODO disable for ingestion
    dbx = DropboxHandler(instance)
    if dbx.dropbox:
        dbx.delete_user_folders()

dashboard/templates/dashboard/dashboard.html
{% extends 'utils/panel_base.html' %}
{% load static %}
{% load gravatar %}
{% load dbx_tags %}
{% block content %}
    <div class="default_row page_content">
        <div class="container">
            <div class="row">
                <div class="col-md-12 col-lg-9">
                    <div class="user">
                        <div class="user_info">
                            <div class="user_avatar">
                                <img src={% gravatar user.email 40 %} alt="Avatar">
                            </div>
                            <div class="user_details">
                                <h3>Welcome<span>[ {{ user.username }} ]</span></h3>
                                <span class="badge badge-light">{{ user.profile.get_account_type_display }}</span>
                                {% if not user.profile.rate_multiplier %}
                                <span id="free_service" class="badge badge-warning" data-container="body"
                                   data-toggle="popover"
                                   data-placement="top" trigger="hover"
                                   data-content="Unlimited rendering service is activated on your account.">Unlimited Rendering Activated</span>
                                {% endif %}
                            </div>
                        </div>
                        <div class="user_status">
                            <div class="credit">
                                <img src="{% static "system/img/credit.svg" %}" alt="credit">
                                <div class="money">
                                    <h3>$ {{ user.profile.balance|floatformat }}</h3>
                                    <span>Your Balance</span>
                                </div>
                                <a href="{% url 'payment' %}" class="btn btn-success" data-toggle="tooltip"
                                   data-placement="top"
                                   title="Add Credit"><i class="fas fa-plus"></i></a>
                            </div>
                            <div class="status">
                                <ul>

                                    <li>
                                        <img src="{% static "system/img/status_jobs.svg" %}" alt="job_status">
                                        <h3>{{ user.profile.job_count }}</h3>
                                        <span>Render Jobs</span>
                                    </li>

                                    <li>
                                        <img src="{% static "system/img/status_payments.svg" %}" alt="payment_status">
                                        <h3>$ {{ user.profile.total_payment|floatformat }}  </h3>
                                        <span>Payments</span>
                                    </li>

                                    <li>
                                        <img src="{% static "system/img/status_invoices.svg" %}" alt="invoices">
                                        <h3>{{ user.profile.payment_count }}</h3>
                                        <span>Invoices</span>
                                    </li>

                                    <li>
                                        <img src="{% static "system/img/status_tickets.svg" %}" alt="tickets">
                                        <h3>{{ user.profile.ticket_count }}</h3>
                                        <span>Support Ticket</span>
                                    </li>

                                </ul>
                            </div>
                        </div>
                    </div>

                    <div class="statistic">
                        <div class="box">
                            <div class="head">
                                <div class="title">
                                    <h4>Render Statistics</h4>
                                </div>
                            </div>
                            <div class="box_content">
                                <div class="chart">
                                    <div id="chart" data-url="{% url 'get_account_chart' %}"></div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="last_jobs">
                        <div class="box">
                            <div class="head">
                                <div class="title">
                                    <h4>Latest Jobs</h4>
                                </div>
                                <div class="options">
                                    <a href="{% url 'job_list' %}" class="btn btn-link">View All</a>
                                </div>
                            </div>
                            <div class="box_content">
                                {% if latest_jobs %}
                                    <ul class="jobs">
                                        {% for job in latest_jobs|slice:":4" %}
                                        <li class="job_box" style="width: 25%">
                                            <div class="software_logo">
                                                <span class="version version_green">{{ job.software_version.version }}</span>
                                                <img src="{{ job.software_version.icon.url }}" alt="software_logo">
                                            </div>
                                            <h5>{{ job.name|truncatechars:20 }}</h5>
                                            <strong class="plan">{{ job.render_plan.display_name }}</strong>
                                            <strong class="cost">{{ job.cost|floatformat }} USD</strong>
                                            <span class="j_stat job_{{ job.status.name }}">{{ job.status.display_name }}</span>
                                        </li>
                                        {% endfor %}
                                    </ul>
                                {% else %}
                                    <div class="empty_list dashboard_empty_list">
										<img src="{% static 'system/img/job_empty.svg' %}" alt="EmptyList">
										<span>No Job Record Found</span>
									</div>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    <div class="last_tickets">
                        <div class="box">
                            <div class="head">
                                <div class="title">
                                    <h4>Last Updated Tickets</h4>
                                </div>
                                <div class="options">
                                    <a href="{% url 'tickets' %}" class="btn btn-link">View All</a>
                                </div>
                            </div>
                            <div class="box_content">
                                {% if latest_tickets %}
                                    <div class="table-responsive-xl">
                                        <table class="table table-hover">
                                            <thead>
                                            <tr>
                                                <th scope="col">Ticket ID</th>
                                                <th scope="col">Subject</th>
                                                <th scope="col">Updated</th>
                                                <th scope="col">Status</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                                {% for ticket in latest_tickets|slice:":5" %}
                                                    <tr>
                                                        <th scope="row">{{ ticket.number }}</th>
                                                        <td><a href="{% url 'tickets' %}?ticket_number={{ ticket.number }}">{{ ticket.subject|truncatechars:20 }}</a></td>
                                                        <td>{{ ticket.date_modified }}</td>
                                                        <td>
                                                            <div class="t_stat ticket_{{ ticket.status }}">{{ ticket.get_status_display }}</div>
                                                        </td>
                                                    </tr>
                                                {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                                {% else %}
                                    <div class="empty_list dashboard_empty_list">
										<img src="{% static 'system/img/ticket.svg' %}" alt="EmptyList">
										<span>No Ticket Record Found</span>
									</div>
                                {% endif %}
                            </div>
                        </div>
                    </div>

                </div>
                <div class="col-md-12 col-lg-3">
                    <div class="dashboard_actions">
                        {% include 'utils/panel_header_actions.html' %}
                    </div>
                    <div class="box">
                        <div class="head">
                            <div class="title">
                                <h4>Job Status Overview</h4>
                            </div>
                        </div>
                        <div class="box_content">
                            <canvas id="job_chart" data-url="{% url 'get_job_chart' %}" width="180" height="180"></canvas>
                        </div>
                    </div>
                    {% include "utils/rendershare_download.html" %}
                    {% for package in payment_packages %}
                        {% if package.show_in_dashboard %}
                            <a href="{% url 'payment' %}" class="box gift" style="background-color: {{package.label_color}}; color: {{package.text_color}};">
                                <img src="{% static "system/img/gift.svg" %}" alt="Gift">
                                <h5>{{ package.description}}</h5>
                                <p>{{ package.extra }}% Extra On {{ package.amount }} USD Purchase</p>
                            </a>
                        {% endif %}
                    {% endfor %}
                {% include "utils/quick_links.html" %}
                </div>
            </div>
        </div>
    </div>
{% endblock content %}
{% block page_scripts %}
    <script src="{% static "system/js/dashboard/dashboard_scripts.js" %}"></script>
{% endblock page_scripts%}