job/urls.py
from django.urls import path
from job import views as job_views
from job import api_views as job_api_views

urlpatterns = [
    path('jobs/job_list/', job_views.JobListView.as_view(), name='job_list'),
    path('jobs/submit_job/', job_views.SubmitJobView.as_view(), name='submit_job'),
    path('jobs/job_output_url/', job_views.job_output_url, name='job_output_url'),
    path('jobs/submit_file_select/get_file_select/', job_views.get_file_select, name='get_file_select'),
    path('jobs/submit_file_select/', job_views.SubmitFileSelectView.as_view(), name='submit_file_select'),
    path('jobs/advanced_keyshot_submitter/', job_views.AdvancedSubmitterView.as_view(), name='advanced_keyshot_submitter'),
    path('jobs/advanced_keyshot_submitter/<uuid:session_id>/', job_views.AdvancedSubmitterView.as_view(), name='advanced_keyshot_submitter'),
    path('jobs/advanced_keyshot_submitter/<str:file_name>/', job_views.AdvancedSubmitterView.as_view(), name='advanced_keyshot_submitter'),
]

# api routes
urlpatterns += [
    path('api-job/job/', job_api_views.JobAPI.as_view()),
    path('api-job/submit_session/', job_api_views.SubmitSessionAPI.as_view()),
]

payment/urls.py
from django.urls import path, re_path
from payment import views as payment_views

urlpatterns = [
    path('payment/', payment_views.PaymentView.as_view(), name='payment'),
    path('payment/cancelled/', payment_views.PaymentView.payment_cancelled, name='payment_cancelled'),
    path('payment/processed/', payment_views.PaymentView.payment_processed, name='payment_processed'),
    path('invoices/', payment_views.InvoiceView.as_view(), name='invoices'),
    path('invoices/generate_invoice/', payment_views.GeneratePDF.as_view(), name='generate_invoice'),
]

ticketing/urls.py
from django.urls import path
from ticketing import views as ticket_views

urlpatterns = [
    path('tickets/', ticket_views.TicketView.as_view(), name='tickets'),
    path('tickets/get_ticket_replies/', ticket_views.TicketView.get_ticket_replies, name='get_ticket_replies'),
    path('tickets/new_ticket/', ticket_views.NewTicketView.as_view(), name='new_ticket'),
]

users/urls.py
from django.urls import path, re_path, include
from users import views as users_views


urlpatterns = [
    path('', users_views.Login.as_view(), name='user_login'),
    path('register/', users_views.Register.as_view(), name='register'),
    path('profile/', users_views.Profile.as_view(), name='profile'),
    path('password_reset/', users_views.UserPasswordResetView.as_view(), name='user_password_reset'),
    path('password_change/', users_views.UserPasswordChangeView.as_view(), name='user_password_change'),
    path('reset/<uidb64>/<token>/', users_views.UserPasswordResetConfirmView.as_view(),
         name='user_password_reset_confirm'),
    path('activate/', users_views.activate, name='activate'),
    path('activate/<slug:username>/', users_views.activate, name='activate'),
    path('activate/<slug:username>/<slug:token>/', users_views.activate, name='activate'),
]

# user rest framework api urls
urlpatterns += [
    path('api-user/user/', users_views.UserAPI.as_view()),
]

ticketing/models.py
from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _
from django.utils import timezone
from django.urls import reverse
from django.template.loader import render_to_string
from django.core.validators import validate_image_file_extension

from rendershot_django.utils import get_random_code
from rendershot_django.utils import post_message_to_slack


class TicketDepartments(models.TextChoices):
    SALES = 'sales', _('Sales')
    TECHNICAL = 'technical', _('Technical')


class TicketStatus(models.TextChoices):
    OPEN = 'open', _('Open')
    PENDING = 'pending', _('Pending')
    RESOLVED = 'resolved', _('Resolved')
    CLOSED = 'closed', _('Closed')
    WAITINGCUSTOMER = 'waiting_on_customer', _('Waiting On Customer')
    WAITINGADMIN = 'waiting_on_admin', _('Waiting On Admin')


class Ticket(models.Model):

    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    number = models.CharField(max_length=20, null=True)
    department = models.CharField(max_length=100, null=True,
                                  choices=TicketDepartments.choices,
                                  default=TicketDepartments.TECHNICAL)
    status = models.CharField(max_length=100, null=True, choices=TicketStatus.choices, default=TicketStatus.OPEN)
    subject = models.CharField(max_length=200, null=True)
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)

    @classmethod
    def post_create(cls, sender, instance, created, *args, **kwargs):
        if created:
            id_string = str(instance.id)
            random_str = get_random_code()
            instance.number = random_str + id_string
            instance.save()

    def __str__(self):
        return self.subject


post_save.connect(Ticket.post_create, sender=Ticket)


class TicketReply(models.Model):

    ticket = models.ForeignKey(Ticket, null=True, on_delete=models.CASCADE)
    author = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    body = models.TextField(null=True, max_length=5000)
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-date_created']

    def __init__(self, *args, **kwargs):
        self.operator = 'web_admin'
        self.signals = {'on_new_reply': self.on_new_reply}
        super(TicketReply, self).__init__(*args, **kwargs)

    def __str__(self):
        return self.author.username + " " + self.ticket.subject

    def save(self, *args, **kwargs):
        pre_save_model = TicketReply.objects.filter(pk=self.pk).first()
        if 'operator' in kwargs:
            self.operator = kwargs.pop('operator')
        super(TicketReply, self).save(*args, **kwargs)

        created = False
        if not pre_save_model and self:
            created = True

        # call signals
        new_reply_event = 'on_new_reply'
        new_reply_signal_func = self.signals.get(new_reply_event)
        if created and new_reply_signal_func:
            new_reply_signal_func(new_reply_event)

    def on_new_reply(self, event):
        if self.author.is_superuser:
            self.email_new_reply()
        self.slack_new_reply(event)

    def slack_new_reply(self, event):
        post_message_to_slack(event, event, {'user': self.author.username, 'reply': self.body}, 'ticket')

    def email_new_reply(self):
        from django.contrib.sites.models import Site
        current_site = Site.objects.get_current()
        site_name = current_site.name
        domain = current_site.domain

        context = {'subject': f'New Admin Message',
                   'description': f'New Message on {self.ticket.subject}',
                   'paragraph_01': f'{self.body}.',
                   'action_text': f'Show Message',
                   'action_url': reverse("tickets") + f"?ticket_number={self.ticket.number}",
                   'current_site': current_site,
                   'domain': domain, 'site_name': site_name,
                   'protocol': 'https', }

        html = render_to_string('email/job_update_email.html',
                                context=context)

        self.ticket.user.email_user(f'New Admin Message', self.ticket.subject, html_message=html)


class TicketAttachment(models.Model):

    reply = models.ForeignKey(TicketReply, null=True, on_delete=models.CASCADE)
    date_created = models.DateTimeField(default=timezone.now)
    attachment = models.ImageField(upload_to='images/%Y-%m-%d/',
                                   null=True,
                                   blank=True,
                                   validators=[validate_image_file_extension])

    def __str__(self):
        return self.attachment.name

ticketing/forms.py
from django import forms
from django.utils.translation import gettext, gettext_lazy as _

from .models import TicketDepartments


class TicketForm(forms.Form):
    department = forms.ChoiceField(label=_("Department"),
                                   choices=TicketDepartments.choices,
                                   widget=forms.Select(
                                   attrs={'autocapitalize': 'none',
                                          'autocomplete': 'department',
                                          'class': "form-control",
                                          'id': '"exampleFormControlSelect1"'})
                                   )

    subject = forms.CharField(label=_("Subject"),
                              strip=False,
                              widget=forms.TextInput(
                              attrs={'autocapitalize': 'none',
                                     'autocomplete': 'subject',
                                     'class': "form-control",
                                     'placeholder': 'Ticket Subject',
                                     'id': 'subject'}))

    body = forms.CharField(widget=forms.Textarea(attrs={'id': 'exampleFormControlTextarea1',
                                                        'rows': 3,
                                                        'placeholder': 'Message',
                                                        'class': "form-control"}))

    attachment = forms.ImageField(label='attachment',
                                  required=False,
                                  widget=forms.ClearableFileInput(attrs={'multiple': True,
                                                                         'class': "custom-file-input",
                                                                         'id': "inputGroupFile01",
                                                                         'aria-describedby': "inputGroupFileAddon01"}))

ticketing/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.utils.decorators import method_decorator
from django.views.generic import View
from django.http import JsonResponse
from django.urls import reverse

from users.decorators import blocked_validation
from .forms import TicketForm
from .models import Ticket, TicketReply, TicketAttachment, TicketStatus


from django.template.loader import render_to_string


class TicketView(View):

    template_name = 'ticketing/tickets.html'

    @method_decorator(blocked_validation)
    @method_decorator(login_required(login_url='user_login'))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def close_ticket(self, selected_ticket):

        selected_ticket.status = TicketStatus.CLOSED
        selected_ticket.save()
        messages.error(self.request, "Requested ticket is closed.")

        return selected_ticket

    def get(self, request, *args, **kwargs):
        tickets = Ticket.objects.order_by('-date_modified').filter(user=request.user)

        ticket_number = self.request.GET.get('ticket_number', '')
        selected_ticket = Ticket.objects.filter(number=ticket_number).first()

        close_ticket = self.request.GET.get('close', '')
        if close_ticket:
            selected_ticket = self.close_ticket(selected_ticket)

        ticket_form = TicketForm()
        return render(self.request, template_name=self.template_name, context={'tickets': tickets,
                                                                               'selected_ticket': selected_ticket,
                                                                               'ticket_form': ticket_form})

    def post(self, request, *args, **kwargs):
        ticket = Ticket.objects.filter(user=request.user, number=request.POST.get('ticket_number')).first()

        if not ticket:
            messages.error(self.request, 'Reply submission failed.')
            return redirect('tickets')

        for file in request.FILES.getlist('attachment'):
            if file.size > 5242880:
                messages.error(self.request, f'Attachment size limit of 5 MB is exceeded : {file.name} .')
                return redirect('tickets')

        new_reply = TicketReply.objects.create(ticket=ticket, author=request.user, body=request.POST.get('body'))
        if not new_reply:
            messages.error(self.request, 'Reply submission failed.')
            return redirect('tickets')

        ticket.status = TicketStatus.WAITINGADMIN
        ticket.save()
        new_reply.save(operator='web_user')

        for file in request.FILES.getlist('attachment'):
            attachment = TicketAttachment.objects.create(reply=new_reply, attachment=file)
            attachment.save()

        messages.success(self.request, 'Your request is successfully submitted, '
                                       'we will get in touch with you as soon as we can.')
        return redirect(f"{reverse('tickets')}?ticket_number={ticket.number}")

    @staticmethod
    def get_ticket_replies(request, *args, **kwargs):
        ticket_number = request.GET.get('ticket_number', None)
        ticket = Ticket.objects.filter(number=ticket_number).first()
        data = {'html_content': ''}

        if not ticket.user == request.user:
            return JsonResponse(data)

        ticket_form = TicketForm()
        html = render_to_string('ticketing/reply_content.html',
                                request=request,
                                context={'selected_ticket': ticket, 'ticket_form': ticket_form})
        data = {'html_content': html}
        return JsonResponse(data)


class NewTicketView(View):

    template_name = 'ticketing/new_ticket.html'

    @method_decorator(blocked_validation)
    @method_decorator(login_required(login_url='user_login'))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get(self, request, *args, **kwargs):

        # this sets initial subject for create report bug
        initial = {}
        if request.GET.get('subject', ""):
            initial['subject'] = request.GET.get('subject')
        ticket_form = TicketForm(initial=initial)

        return render(self.request,
                      template_name=self.template_name,
                      context={'ticket_form': ticket_form})

    def post(self, request, *args, **kwargs):

        ticket = Ticket.objects.create(user=request.user,
                                       department=request.POST.get('department'),
                                       subject=request.POST.get('subject'))
        if not ticket:
            messages.error(self.request, 'Ticket submission failed.')
            return redirect('new_ticket')

        for file in request.FILES.getlist('attachment'):
            if file.size > 5242880:
                messages.error(self.request, f'Attachment size limit of 5 MB is exceeded : {file.name} .')
                return redirect('new_ticket')

        if ticket.ticketreply_set.all():
            ticket.status = TicketStatus.WAITINGADMIN
        ticket.save()

        ticket_reply = TicketReply.objects.create(ticket=ticket, author=request.user, body=request.POST.get('body'))
        if not ticket_reply:
            messages.error(self.request, 'Ticket submission failed.')
            return redirect('new_ticket')

        ticket_reply.save(operator='web_user')

        for file in request.FILES.getlist('attachment'):
            attachment = TicketAttachment.objects.create(reply=ticket_reply, attachment=file)
            attachment.save()

        messages.success(self.request, 'Your request is successfully submitted, '
                                       'we will get in touch with you as soon as we can.')
        return redirect(f"{reverse('tickets')}?ticket_number={ticket.number}")

ticketing/templates/ticketing/reply_content.html
{% load static %}
{% if selected_ticket.ticketreply_set.all %}
    <div class="tab-content" id="v-pills-tabContent">
        <div class="tab-pane fade show active" id="v-pills-home" role="tabpanel"
             aria-labelledby="v-pills-home-tab">
            <div class="row">
                <div class="col-12 col-md-12 col-lg-9 col-xl-9">
                    <div class="ticket_content">
                        <div class="head">
                            <h4>{{ selected_ticket.subject }}</h4>
                            <a class="btn btn-primary" data-toggle="collapse"
                               href="#answer" role="button" aria-expanded="false"
                               aria-controls="answer">Answer</a>
                        </div>
                        <div class="ticket_conversation">
                            <div class="collapse" id="answer">
                                <div class="box">
                                    <div class="box_content">
                                        <form method="post" enctype="multipart/form-data">
                                            {% csrf_token %}
                                            <div class="row">
                                                <div class="col-12">
                                                    <input type="hidden" name="ticket_number" value={{ selected_ticket.number }}>
                                                    <div class="form-group">
                                                        {{ ticket_form.body}}
                                                    </div>
                                                    <div class="input-group mb-3">
                                                        <div class="input-group-prepend">
                                                            <span class="input-group-text" id="inputGroupFileAddon01">Upload</span>
                                                        </div>
                                                        <div class="custom-file">
                                                            {{ ticket_form.attachment }}
                                                            <label class="custom-file-label" for="inputGroupFile01">Choose
                                                                file</label>
                                                        </div>
                                                    </div>
                                                    <div class="form-group mt-2">
                                                        <button type="submit" class="btn btn-primary">
                                                            Submit Answer
                                                        </button>
                                                    </div>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                            <div class="conversation">
                                {% for reply in selected_ticket.ticketreply_set.all %}
                                    {% if reply.author.is_superuser %}
                                        <div class="box stuff">
                                    {% else %}
                                        <div class="box">
                                    {% endif %}
                                <div class="box_content">
                                    <div class="row">
                                        <div class="col-12 col-md-9 col-lg-9 col-xl-9">
                                            {{ reply.body|linebreaks|urlize }}
                                            {% if reply.ticketattachment_set.all %}
                                                {% for file in reply.ticketattachment_set.all %}
                                                    <a href={{ file.attachment.url }} class="attachment" target="_blank">{{ file.attachment.name }}</a>
                                                {% endfor %}
                                            {% endif %}
                                        </div>
                                        <div class="col-12 col-md-3 col-lg-3 col-xl-3">
                                            <span>{{ reply.author.username }}</span>
                                            <span>{{ reply.date_modified }}</span>
                                        </div>
                                    </div>
                                </div>
                                </div>
                                {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-12 col-md-12 col-lg-3 col-xl-3">
                        <div class="ticket_details">
                            <ul>
                                <li>
                                    <i class="far fa-calendar-check"></i>
                                    <strong>Ticket Number:</strong>
                                    <span>{{ selected_ticket.number }}</span>
                                </li>
                                <li>
                                    <i class="fab fa-creative-commons-nd"></i>
                                    <strong>Department:</strong>
                                    <span>{{ selected_ticket.get_department_display }}</span>
                                </li>
                                <li>
                                    <i class="far fa-clock"></i>
                                    <strong>Submitted:</strong>
                                    <span>{{ selected_ticket.date_created }}</span>
                                </li>
                                <li>
                                    <i class="fas fa-history"></i>
                                    <strong>Last Updated:</strong>
                                    <span>{{ selected_ticket.date_modified }}</span>
                                </li>
                                <li>
                                    <i class="far fa-flag"></i>
                                    <strong>Status:</strong>
                                    <div class="t_stat ticket_{{ selected_ticket.status }}">{{ selected_ticket.get_status_display }}</div>
                                </li>
                                <a href="{% url 'tickets' %}?ticket_number={{ selected_ticket.number }}&close=True" class="btn btn-danger">Close Ticket</a>
                            </ul>
                        </div>
                    </div>
                </div>

            </div>
            <div class="tab-pane fade" id="v-pills-profile" role="tabpanel"
                 aria-labelledby="v-pills-profile-tab">

                <div class="row">
                    <div class="col-10">
                        profile
                    </div>
                    <div class="col-2">
                        profile Details
                    </div>
                </div>
            </div>
            <div class="tab-pane fade" id="v-pills-messages" role="tabpanel"
                 aria-labelledby="v-pills-messages-tab">

                <div class="row">
                    <div class="col-10">
                        messages
                    </div>
                    <div class="col-2">
                        messages Details
                    </div>
                </div>
            </div>
            <div class="tab-pane fade" id="v-pills-settings" role="tabpanel"
                 aria-labelledby="v-pills-settings-tab">

                <div class="row">
                    <div class="col-10">
                        settings
                    </div>
                    <div class="col-2">
                        settings Details
                    </div>
                </div>
            </div>
        </div>
{% else %}
        <div class="row justify-content-center">
            <div class="ticket_empty_content">
                <img src="{% static "system/img/ticket_empty_imgage.svg" %}" alt="Do you have a question?">
                <h3>Do you have a question?</h3>
                <p>If you see a problem in our services or if you have any questions, you can contact the experts of
                    the support unit by filling out the form below.</p>
                <a href="{% url 'new_ticket' %}" class="btn btn-primary">Submit Ticket</a>
            </div>
        </div>
{% endif %}

ticketing/templates/ticketing/tickets.html
{% extends 'utils/panel_base.html' %}
{% load static %}
{% block content %}
    <div class="header">
        <div class="container">
            <div class="row">
                <div class="col-12 col-md-6 col-lg-8 col-xl-8">
                    <div class="title">
                        <img src="{% static "system/img/support_tm.svg" %}" alt="Tickets">
                        <h1>Support Ticket</h1>
                    </div>
                </div>
                <div class="col-12 col-md-6 col-lg-4 col-xl-4">
                    {% include 'utils/panel_header_actions.html' %}
                </div>
            </div>
        </div>
        <div class="header_item">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <ul class="nav">
                            <li class="nav-item active">
                                <a class="nav-link" href="#">Support Ticket</a>
                            </li>
                            <li class="nav-item new_ticket_nav">
                                <a class="nav-link" href="{% url 'new_ticket' %}"><i class="fas fa-ticket-alt"></i>Submit
                                    New Ticket</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="content tickets">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    {% include 'utils/messages.html' %}
                </div>
            </div>
            <div class="row">
                <div class="col-12 col-md-12 col-lg-3 col-xl-3">
                    <div class="box ticket_list">
                        <div class="head">
                            <div class="title">
                                <h4>Ticket List</h4>
                            </div>

                            <div class="search-box">
                                <input type="text" class="search-txt" placeholder="Search ..." , id="ticket_search">
                                <a class="search-btn">
                                    <i class="fas fa-search"></i>
                                </a>
                            </div>

                        </div>

                        {% if tickets %}
                            <div class="box_content" id="tickets_list">
                                <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist"
                                     aria-orientation="vertical">
                                    {% for ticket in tickets %}
                                        {% if ticket.number == selected_ticket.number %}
                                            <a class="nav-link show active " data-toggle="pill"
                                        {% else %}
                                            <a class="nav-link" data-toggle="pill"
                                        {% endif %}
                                               id="{{ ticket.number }}"
                                               onclick="request_ticket_replies(`{% url "get_ticket_replies" %}`,`{{ ticket.number }}`);"
                                               href="#v-pills-home"
                                               role="tab" aria-controls="v-pills-home" aria-selected="true">
                                        <h5>{{ ticket.subject }}</h5>
                                        <div class="t_stat ticket_{{ ticket.status }}">{{ ticket.get_status_display }}</div>
                                        <span>{{ ticket.date_modified }}</span>

                                    </a>
                                    {% endfor %}
                                </div>
                            </div>
                        {% else %}
                            <div class="box_content empty_list" id="replies_box">

                                <img src="{% static "system/img/ticket.svg" %}" alt="Empty List">
                                <span>Ticket Not Found</span>

                            </div>
                        {% endif %}
                        <div class="foot">
                            <div class="btn-group dropup">
                                <a class="btn btn-link dropdown-toggle" data-toggle="dropdown"
                                   aria-haspopup="true" aria-expanded="false">
                                    <i class="fas fa-filter"></i>Filter
                                </a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" href="">Remove Filters</a>
                                    <a class="dropdown-item" href="#">Open</a>
                                    <a class="dropdown-item" href="#">Closed</a>
                                    <a class="dropdown-item" href="#">Resolved</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-12 col-md-12 col-lg-9 col-xl-9" id="replies_content">
                    {% include 'ticketing/reply_content.html' %}
                </div>
            </div>
        </div>
    </div>

{% endblock content %}
{% block page_scripts %}
    <script src="{% static "system/js/ticket/main.js" %}"></script>
    <script src="{% static "system/js/ticket/tickets_scripts.js" %}"></script>
{% endblock page_scripts %}