job/urls.py
from django.urls import path
from job import views as job_views
from job import api_views as job_api_views

urlpatterns = [
    path('jobs/job_list/', job_views.JobListView.as_view(), name='job_list'),
    path('jobs/submit_job/', job_views.SubmitJobView.as_view(), name='submit_job'),
    path('jobs/job_output_url/', job_views.job_output_url, name='job_output_url'),
    path('jobs/submit_file_select/get_file_select/', job_views.get_file_select, name='get_file_select'),
    path('jobs/submit_file_select/', job_views.SubmitFileSelectView.as_view(), name='submit_file_select'),
    path('jobs/advanced_keyshot_submitter/', job_views.AdvancedSubmitterView.as_view(), name='advanced_keyshot_submitter'),
    path('jobs/advanced_keyshot_submitter/<uuid:session_id>/', job_views.AdvancedSubmitterView.as_view(), name='advanced_keyshot_submitter'),
    path('jobs/advanced_keyshot_submitter/<str:file_name>/', job_views.AdvancedSubmitterView.as_view(), name='advanced_keyshot_submitter'),
]

# api routes
urlpatterns += [
    path('api-job/job/', job_api_views.JobAPI.as_view()),
    path('api-job/submit_session/', job_api_views.SubmitSessionAPI.as_view()),
]

payment/urls.py
from django.urls import path, re_path
from payment import views as payment_views

urlpatterns = [
    path('payment/', payment_views.PaymentView.as_view(), name='payment'),
    path('payment/cancelled/', payment_views.PaymentView.payment_cancelled, name='payment_cancelled'),
    path('payment/processed/', payment_views.PaymentView.payment_processed, name='payment_processed'),
    path('invoices/', payment_views.InvoiceView.as_view(), name='invoices'),
    path('invoices/generate_invoice/', payment_views.GeneratePDF.as_view(), name='generate_invoice'),
]

rendershot_django/urls.py
import os
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, re_path, include
from rest_framework.routers import DefaultRouter
from rest_framework.authtoken import views

rest_framework_router = DefaultRouter()

urlpatterns = [
    path(os.getenv('SECRET_ADMIN_URL') + '/admin/', admin.site.urls),
    path('', include('job.urls')),
    path('', include('users.urls')),
    path('', include('dashboard.urls')),
    path('', include('payment.urls')),
    path('', include('ticketing.urls')),
    path('', include('system.urls')),
    re_path(r'^jet/', include('jet.urls', 'jet')),  # Django JET URLS
    path("admin/", include('loginas.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    re_path(r'^advanced_filters/', include('advanced_filters.urls')),
    re_path(r'^_nested_admin/', include('nested_admin.urls')),
]

# rest framework api urls
urlpatterns += [
    path('api-auth/token/', views.obtain_auth_token),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path, re_path, include
from users import views as users_views


urlpatterns = [
    path('', users_views.Login.as_view(), name='user_login'),
    path('register/', users_views.Register.as_view(), name='register'),
    path('profile/', users_views.Profile.as_view(), name='profile'),
    path('password_reset/', users_views.UserPasswordResetView.as_view(), name='user_password_reset'),
    path('password_change/', users_views.UserPasswordChangeView.as_view(), name='user_password_change'),
    path('reset/<uidb64>/<token>/', users_views.UserPasswordResetConfirmView.as_view(),
         name='user_password_reset_confirm'),
    path('activate/', users_views.activate, name='activate'),
    path('activate/<slug:username>/', users_views.activate, name='activate'),
    path('activate/<slug:username>/<slug:token>/', users_views.activate, name='activate'),
]

# user rest framework api urls
urlpatterns += [
    path('api-user/user/', users_views.UserAPI.as_view()),
]

payment/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _
from django.db.models.signals import post_save
from django.urls import reverse

from colorfield.fields import ColorField
from rendershot_django.utils import get_random_code, post_message_to_slack, send_update_email


class Currencies(models.TextChoices):
    USD = 'usd', _('usd')


class PaymentTypes(models.TextChoices):
    PAYPAL = 'paypal', _('Paypal')
    COUPON = 'coupon', _('Coupon')
    CREDIT_REFUND = 'credit_refund', _('Credit Refund')
    PAYMENT_REFUND = 'payment_refund', _('Payment Refund')
    CREDIT_TRANSFER = 'credit_transfer', _('Credit Transfer')
    PROMOTION = 'promotion', _('Promotion')
    COST_BALANCE = 'cost_balance', _('Cost Balance')


class PaymentStatus(models.TextChoices):
    INITIATED = 'initiated', _('Initiated')
    PENDING = 'pending', _('Pending')
    COMPLETED = 'completed', _('Completed')
    CANCELLED = 'cancelled', _('Cancelled')
    INVALID = 'invalid', _('Invalid')


class Payment(models.Model):

    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    type = models.CharField(max_length=100, null=True, choices=PaymentTypes.choices, default=PaymentTypes.PAYPAL)
    status = models.CharField(max_length=100, null=True, choices=PaymentStatus.choices, default=PaymentStatus.INITIATED)
    amount = models.FloatField(default=5.0, null=True)
    payment_id = models.CharField(max_length=200, null=True, blank=True)
    order_data = models.JSONField(null=True, blank=True)
    payment_data = models.JSONField(null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    currency = models.CharField(max_length=100, null=True, choices=Currencies.choices, default=Currencies.USD)

    def __init__(self, *args, **kwargs):
        self.status_signals = {'on_initiated': self.on_initiated,
                               'on_pending': self.on_pending,
                               'on_completed': self.on_completed,
                               'on_cancelled': self.on_cancelled,
                               'on_invalid': self.on_invalid}

        super(Payment, self).__init__(*args, **kwargs)

    def save(self, *args, **kwargs):
        pre_save_model = Payment.objects.filter(pk=self.pk).first()
        super(Payment, self).save(*args, **kwargs)

        if not pre_save_model:
            self.created = True

        call_status_signals = True
        if pre_save_model and pre_save_model.status == self.status:
            call_status_signals = False

        status_signal = self.status_signals.get(f'on_{self.status.lower()}', None)
        call_status_signals and status_signal and status_signal()

    def on_initiated(self):
        self.slack_payment_update('on_payment_initiated')

    def on_pending(self):
        self.slack_payment_update('on_payment_pending')

    def on_completed(self):

        if self.type == PaymentTypes.PAYPAL:
            self.user.profile.credit += self.amount
        elif self.type == PaymentTypes.COUPON:
            self.user.profile.credit += self.amount
        elif self.type == PaymentTypes.CREDIT_REFUND:
            self.user.profile.credit += self.amount
        elif self.type == PaymentTypes.PAYMENT_REFUND:
            self.user.profile.credit -= self.amount
        elif self.type == PaymentTypes.CREDIT_TRANSFER:
            self.user.profile.credit += self.amount
        elif self.type == PaymentTypes.PROMOTION:
            self.user.profile.credit += self.amount
        elif self.type == PaymentTypes.COST_BALANCE:
            self.user.profile.credit -= self.amount  # could be negative

        self.user.save()
        self.email_payment_update()
        self.slack_payment_update('on_payment_completed')

    def on_cancelled(self):
        self.slack_payment_update('on_payment_cancelled')

    def on_invalid(self):
        self.slack_payment_update('on_payment_invalid')

    def get_email_subject(self):
        subject = 'Update'

        if self.type == PaymentTypes.PAYPAL:
            subject = 'Payment Update'
        elif self.type == PaymentTypes.COUPON:
            subject = 'Coupon Update'
        elif self.type == PaymentTypes.CREDIT_REFUND:
            subject = 'Credit Refund Update'
        elif self.type == PaymentTypes.PAYMENT_REFUND:
            subject = 'Payment Refund Update'
        elif self.type == PaymentTypes.CREDIT_TRANSFER:
            subject = 'Credit Transfer Update'
        elif self.type == PaymentTypes.PROMOTION:
            subject = 'Payment Promotion Update'
        elif self.type == PaymentTypes.COST_BALANCE:
            subject = 'Cost Balance Update'

        return subject

    def get_message_subject(self):
        message = 'Payment'

        if self.type == PaymentTypes.PAYPAL:
            message = f'Payment {self.payment_id} {self.status.capitalize()}'
        elif self.type == PaymentTypes.COUPON:
            message = f'Coupon Processed'
        elif self.type == PaymentTypes.CREDIT_REFUND:
            message = f'Credit Refund Processed'
        elif self.type == PaymentTypes.PAYMENT_REFUND:
            message = f'Payment Refund Processed'
        elif self.type == PaymentTypes.CREDIT_TRANSFER:
            message = f'Credit Transfer Processed'
        elif self.type == PaymentTypes.PROMOTION:
            message = f'Payment Promotion Processed'
        elif self.type == PaymentTypes.COST_BALANCE:
            message = f'Cost Balance Processed'

        return message

    def email_payment_update(self):
        # TODO disable for ingestion
        subject = self.get_email_subject()
        message = self.get_message_subject()

        context = {'subject': subject,
                   'description': message,
                   'paragraph_01': f'This is a official receipt/confirmation for : {self.payment_id}.\n'
                                   f'Amount : {self.amount}\n'
                                   f'Current Balance : {self.user.profile.balance}',
                   'paragraph_02': f'You can view and download invoices for the payments in your online panel',
                   'action_text': f'Payment List',
                   'action_url': reverse("invoices")}

        send_update_email(self.user, context, subject, message)

    def slack_payment_update(self, event):
        # TODO disable for ingestion
        data = {'user': self.user.username,
                'user_balance': self.user.profile.balance,
                'type': self.type,
                'status': self.status,
                'amount': self.amount,
                'payment_id': self.payment_id,
                }

        post_message_to_slack(event, event, data)


class PromotionPackage(models.Model):

    name = models.CharField(max_length=100, null=True)
    description = models.CharField(max_length=100, null=True)
    amount = models.FloatField(default=0.0, null=True)
    extra = models.IntegerField(default=0, null=True)
    show_in_dashboard = models.BooleanField(default=False, null=True)
    label_color = ColorField(default='#DF3F60', null=True)
    text_color = ColorField(default='#FFF', null=True)


class CouponCodes(models.Model):
    code = models.CharField(max_length=20, blank=True, null=True, unique=True)
    is_redeemed = models.BooleanField(default=False, null=True)
    amount = models.FloatField(default=0.0, null=True, blank=True)

    @classmethod
    def post_create(cls, sender, instance, created, *args, **kwargs):
        if created:
            id_string = str(instance.id)
            random_str = get_random_code(lenght=7)
            instance.code = random_str + id_string
            instance.save()

    def __str__(self):
        return "%s" % (self.code,)


post_save.connect(CouponCodes.post_create, sender=CouponCodes)

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver
from django.utils.translation import gettext_lazy as _
import pytz
from rest_framework.authtoken.models import Token

from payment.models import PaymentStatus
from rendershot_django.utils import post_message_to_slack
from system.dbx_utils import DropboxHandler


class AccountTypes(models.TextChoices):
    PERSONAL = 'personal', _('Personal')
    COMPANY = 'company', _('Company')


class Profile(models.Model):

    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    account_type = models.CharField(max_length=100, null=True, choices=AccountTypes.choices, default=AccountTypes.PERSONAL)
    company_name = models.CharField(max_length=100, null=True)
    city = models.CharField(max_length=100, null=True)
    country = models.TextField(max_length=50, null=True, choices=pytz.country_names.items())
    address = models.CharField(max_length=1000, null=True)
    zip_code = models.CharField(max_length=100, null=True)
    phone = models.CharField(max_length=100, null=True)
    vat = models.CharField(max_length=100, null=True)
    payment_allowed = models.BooleanField(default=False, null=True)
    credit = models.FloatField(default=0.0, null=True)
    blocked = models.BooleanField(default=False, null=True)
    receive_job_email_notifs = models.BooleanField(default=True, null=True)
    ip_address = models.CharField(max_length=250, null=True)
    dropbox_outputs_share_link = models.CharField(max_length=250, null=True)
    rate_multiplier = models.FloatField(default=1.0, null=True)
    reset_password_required = models.BooleanField(default=False, null=True)
    chunk_size_override = models.IntegerField(default=1, null=True)

    def __str__(self):
        return self.user.username

    @property
    def total_payment(self):
        total = 0
        for payment in self.user.payment_set.all():
            if type(payment.amount) in [int, float] and payment.status == PaymentStatus.COMPLETED:
                total += payment.amount
        return total

    @property
    def payment_count(self):
        return len(self.user.payment_set.all())

    @property
    def ticket_count(self):
        return len(self.user.ticket_set.all())

    @property
    def job_count(self):
        return len(self.user.job_set.exclude(status__name='deleted').all())

    @property
    def balance(self):
        jobs = self.user.job_set.all()
        spent_amount = float()

        for job in jobs:
            spent_amount += job.cost

        balance = self.credit - (spent_amount * self.user.profile.rate_multiplier)
        return balance

    def is_network_rendering_allowed(self):
        return self.user.groups.filter(name='network_rendering').exists()


@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        Token.objects.create(user=instance)
        Profile.objects.create(user=instance)
        # TODO disable for ingestion
        post_message_to_slack("New Registration",
                              f"New User : {instance.username} Registered",
                              {'user': instance.username,
                               'email': instance.email})

    instance.profile.save()


@receiver(post_delete, sender=User)
def update_user_dropbox(sender, instance, **kwargs):

    # TODO disable for ingestion
    dbx = DropboxHandler(instance)
    if dbx.dropbox:
        dbx.delete_user_folders()

payment/forms.py
from django import forms
from django.forms.widgets import ChoiceWidget
from django.utils.translation import gettext, gettext_lazy as _
from django.core.validators import RegexValidator

from payment.models import *
numeric = RegexValidator(r'^[0-9+]', 'Only digit characters.')


class PromotionPackageCustomRadioSelect(ChoiceWidget):
    input_type = 'radio'
    template_name = 'payment/promotion_package_radio_widget.html'
    option_template_name = 'payment/promotion_package_radio_option_widget.html'


class PaymentForm(forms.Form):
    request_type = forms.CharField(required=False, widget=forms.HiddenInput(attrs={'id': 'request_type'}))

    payment_amount = forms.FloatField(label=_("Amount"),
                                      initial=30,
                                      max_value=1000,
                                      min_value=30,
                                      validators=[numeric],
                                      widget=forms.NumberInput(
                                      attrs={'class': "form-control",
                                             'placeholder': 'Enter Amount',
                                             'aria-label': "Enter Amount",
                                             'aria-describedby': "basic-addon2",
                                             'id': 'amount'})
                                      )

    promotion_package = forms.ModelChoiceField(label=_("Promotion Package"),
                                               initial=PromotionPackage.objects.first,
                                               queryset=PromotionPackage.objects.all(),
                                               widget=PromotionPackageCustomRadioSelect(
                                               attrs={'class': "form-control",
                                                      'id': 'promotion_package',
                                                      'autocomplete': False}))

    coupon_code = forms.CharField(label=_("Coupon Code"),
                                  max_length=20,
                                  min_length=8,
                                  widget=forms.TextInput(
                                  attrs={'class': "form-control",
                                         'placeholder': 'Enter Coupon Code',
                                         'id': 'inputCouponCode'})
                                  )

payment/templates/payment/invoice_template.html
{% load static %}
<!doctype html>
<html lang="en">
<head>

    <style type="text/css">
        @page {
            size: A4;
            margin: 1cm;
        }

        h1 {
            color: #0040BF;
            font-size: 30px;
            margin: 0;
            text-align: left;
        }

        .header td {
            border: 1px solid #fff;
            padding-top: 0;
            padding-left: 0;
            padding-right: 0;
            padding-bottom: 10px;
            text-align: left;
        }



        .header td strong {
            font-size: 15px;
        }


        .stat_paid {
            color: #00B712;

        }

        .table, td, th {
            border: 1px solid #F1F5F8;
            text-align: left;
            color: #38596A;
        }

        .table {
            border-collapse: collapse;
            width: 100%;
            margin-bottom: 20px;
            font-size: 13px;

        }

        ul {
            padding: 0;
            margin-bottom: 0;

        }

        li {
            margin-left: 20px;
        }


        .table th, td {
            text-align: left;

        }

        th {
            padding-top: 8px;
            padding-left: 8px;
            padding-right: 8px;
            padding-bottom: 3px;
            background-color: #F2F8FC;
        }

        td {
            padding-top: 8px;
            padding-left: 8px;
            padding-right: 8px;
            padding-bottom: 3px;
            word-break: inherit;
        }

        .information th {
            background-color: #0040BF;
            color: #fff;
        }

        .information td {
            padding-top: 20px;
            padding-left: 8px;
            padding-right: 8px;
            padding-bottom: 20px;
        }

        h5 {
            font-size: 15px;
        }

        p {
            font-size: 13px;
            color: #A2B7C1;
            text-align: center;
        }


    </style>

</head>
<body>


<table class="header">
    <tbody>
    <tr>
        <td>
            <img src="{% static "system/img/pdf_logo.png" %}" alt="RenderShot">

        </td>
        <td style="text-align: right"><strong>
            Status:
            <span class="stat_paid">{{ payment.get_status_display }}</span>
        </strong></td>
    </tr>
    </tbody>
</table>

<table class="table txid">
    <tbody>
    <tr>
        <td>
            <strong>Transaction ID: <span>{{ payment.payment_id }}</span></strong>
        </td>
        <td>
            <strong>Invoice Date: <span>{{ payment.date_created }}</span></strong>
        </td>
    </tr>
    </tbody>
</table>


<table class="table information">
    <tbody>
    <tr>
        <th>Invoiced To</th>
        <th>Pay To</th>
    </tr>
    <tr>
        <td>
            <ul>
                {% if user.profile.company_name %}
                    <li>{{ user.profile.company_name }}</li>
                {% endif %}
                {% if user.first_name or user.last_name%}
                    <li>{% if user.first_name %}{{ user.first_name }}{% endif %} {% if user.last_name %}{{ user.last_name }}{% endif %}</li>
                {% endif %}
                {% if user.profile.address %}
                    <li>{{ user.profile.address }}</li>
                {% endif %}
                {% if user.profile.city %}
                    <li>{{ user.profile.city }}</li>
                {% endif %}
                {% if user.profile.get_country_display %}
                    <li>{{ user.profile.get_country_display }}</li>
                {% endif %}
                {% if user.profile.zip_code %}
                    <li>{{ user.profile.zip_code }} </li>
                {% endif %}
                {% if user.profile.vat %}
                    <li> VAT {{ user.profile.vat }}</li>
                {% endif %}
            </ul>
        </td>
        <td>
            <ul>
                {% if admin.profile.company_name %}
                    <li>{{ admin.profile.company_name }}</li>
                {% endif %}
                {% if admin.first_name or admin.last_name%}
                    <li>{% if admin.first_name %}{{ admin.first_name }}{% endif %} {% if admin.last_name %}{{ admin.last_name }}{% endif %}</li>
                {% endif %}
                {% if admin.profile.address %}
                    <li>{{ admin.profile.address }}</li>
                {% endif %}
                {% if admin.profile.city %}
                    <li>{{ admin.profile.city }}</li>
                {% endif %}
                {% if admin.profile.get_country_display %}
                    <li>{{ admin.profile.get_country_display }}</li>
                {% endif %}
                {% if admin.profile.zip_code %}
                    <li>{{ admin.profile.zip_code }} </li>
                {% endif %}
            </ul>
        </td>
    </tr>
    </tbody>
</table>


<table class="table">
    <thead>
    <tr>
        <th scope="col">Items</th>
        <th scope="col">Total</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>Inv-{{ payment.payment_id }}</td>
        <td>{{ payment.amount|floatformat }} USD</td>
    </tr>
    </tbody>
</table>
<h5>Transactions</h5>
<table class="table">
    <thead>
    <tr>
        <th scope="col">Transaction Date</th>
        <th scope="col">Gateway</th>
        <th scope="col">Transaction ID</th>
        <th scope="col">Amount</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>{{ payment.date_created }}</td>
        <td>{{ payment.get_type_display }}</td>
        <td>{{ payment.payment_id }}</td>
        <td>{{ payment.amount|floatformat }} USD</td>
    </tr>
    </tbody>
</table>
<h5>Details</h5>
<table class="table">
    <thead>
    <tr>
        <th scope="col">Description</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>KeyShot Cloud Rendering Services</td>
    </tr>
    </tbody>
</table>


<p>PDF Invoice Generated {{ today }}</p>
</body>
</html>

payment/templates/payment/invoices.html
{% extends 'utils/panel_base.html' %}
{% load static %}
{% block content %}

    <div class="header">
        <div class="container">
            <div class="row">
                <div class="col-12 col-md-6 col-lg-8 col-xl-8">
                    <div class="title">
                        <img src="{% static "system/img/payment_tm.svg" %}">
                        <h1>Payment</h1>
                    </div>
                </div>
                <div class="col-12 col-md-6 col-lg-4 col-xl-4">
                    {% include 'utils/panel_header_actions.html' %}
                </div>
            </div>
        </div>
        <div class="header_item">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <ul class="nav">
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'payment' %}">Add Fund</a>
                            </li>
                            <li class="nav-item active">
                                <a class="nav-link" href="#">Invoices</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="content">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="rs_table">
                        {% include 'utils/messages.html' %}
                        <div class="table-responsive-xl">
                            <table class="table table-hover">
                                <thead>
                                <tr>
                                    <th scope="col">Invoice id</th>
                                    <th scope="col">Date</th>
                                    <th scope="col">Transaction ID</th>
                                    <th scope="col">Amount</th>
                                    <th scope="col">Type</th>
                                    <th scope="col">Status</th>
                                    <th scope="col">Action</th>
                                </tr>
                                </thead>
                                <tbody class="infinite-container">
                                {% for payment in payments %}
                                    <tr class="infinite-item">
                                        <td scope="row">Inv-{{ payment.payment_id|truncatechars:30 }}</td>
                                        <td>{{ payment.date_created }}</td>
                                        <td>{{ payment.payment_id|truncatechars:40 }}</td>
                                        <td><strong>{{ payment.amount|floatformat  }} USD</strong></td>
                                        <td><strong>{{ payment.get_type_display }}</strong></td>
                                        <td><span class="i_stat invoice_{{ payment.status }}">{{ payment.get_status_display }}</span></td>
                                        <td><a href="{% url 'generate_invoice' %}?payment_id={{ payment.payment_id }}" class="btn btn-light"><i class="fas fa-print"></i></a></td>
                                    </tr>
                                {% endfor %}
                                <div class="table_footer text-center loading" style="display: none;">
                                    <a href="">Loading More...</a>
                                </div>
                                {% if page_obj.has_next %}
                                    <a class="infinite-more-link" href="?page={{ page_obj.next_page_number }}"></a>
                                {% endif %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}
{% block page_scripts %}
    <script>
        let infinite = new Waypoint.Infinite({
            element: $('.infinite-container')[0],
            onBeforePageLoad: function () {
                $('.loading').show();
            },
            onAfterPageLoad: function ($items) {
                $('.loading').hide();
            }
        });
    </script>
{% endblock page_scripts %}

payment/templates/payment/promotion_package_radio_option_widget.html
<label class="btn btn-outline-primary btn-lg active">
<input type="{{ widget.type }}"
       id="{{ widget.value.id }}"
       name="{{ widget.name }}"
       {% if widget.value != None %}value="{{ widget.value.instance.id|stringformat:'s' }}"{% endif %}
       {% include "django/forms/widgets/attrs.html" %}>
<i class="badge">Extra: % {{ widget.value.instance.extra|stringformat:'s' }}</i>
<strong>{{ widget.value.instance.amount|stringformat:'s' }} USD</strong>
<span>{{ widget.value.instance.name|stringformat:'s' }}</span>
</label>


{#{% if widget.wrap_label %}<label{% if widget.attrs.id %}#}
{#    for="{{ widget.attrs.id }}"{% endif %}>{% endif %}{% include "django/forms/widgets/input.html" %}#}
{#{% if widget.wrap_label %} {{ widget.label }}</label>{% endif %}#}

payment/templates/payment/promotion_package_radio_widget.html
{% for group, options, index in widget.optgroups %}
    {% for widget in options %}
        {% include widget.template_name %}
    {% endfor %}
{% endfor %}
{##}
{#{% with id=widget.attrs.id %}#}
{#    <ul{% if id %} id="{{ id }}"{% endif %}{% if widget.attrs.class %} class="{{ widget.attrs.class }}"{% endif %}>#}
{#        {% for group, options, index in widget.optgroups %}#}
{#            {% if group %}#}
{#                <li>{{ group }}#}
{#                <ul{% if id %} id="{{ id }}_{{ index }}"{% endif %}>{% endif %}#}
{#            {% for widget in options %}#}
{#                <li>{% include widget.template_name %}</li>{% endfor %}{% if group %}#}
{#                </ul></li>#}
{#            {% endif %}#}
{#        {% endfor %}#}
{#    </ul>#}
{#{% endwith %}#}